# Generated by Django 2.1.7 on 2020-01-16 04:52

from django.db import migrations, models
import django.db.models.deletion
import voucher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense_voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=voucher.models.increment_Activity_id, max_length=100, null=True)),
                ('employee_fname', models.CharField(max_length=100, null=True)),
                ('employee_lname', models.CharField(max_length=100, null=True)),
                ('employee_group', models.CharField(max_length=100, null=True)),
                ('employee_cost', models.CharField(max_length=100, null=True)),
                ('new_employee_id', models.CharField(max_length=100, null=True)),
                ('new_employee_fname', models.CharField(max_length=100, null=True)),
                ('new_employee_lname', models.CharField(max_length=100, null=True)),
                ('new_employee_group', models.CharField(max_length=100, null=True)),
                ('new_employee_cost', models.CharField(max_length=100, null=True)),
                ('fleet_area', models.CharField(choices=[('The Globe Tower', 'The Globe Tower'), ('Visayas-Mindanao', 'Visayas-Mindanao')], max_length=100, null=True)),
                ('received_voucher', models.DateField(null=True)),
                ('trans_type', models.CharField(choices=[('Gas Reimbursements', 'Gas Reimbursements'), ('Car Parts Replacement', 'Car Parts Replacement'), ('GR and CPR', 'GR and CPR')], max_length=100, null=True)),
                ('voucher_no', models.CharField(max_length=100, null=True)),
                ('voucher_amount', models.CharField(max_length=100, null=True)),
                ('voucher_type', models.CharField(choices=[('Expense Voucher', 'Expense Voucher'), ('Petty Cash Voucher', 'Petty Cash Voucher'), ('EV and PCV', 'EV and PCV')], max_length=100, null=True)),
                ('fuel_amount', models.CharField(max_length=100, null=True)),
                ('fuel_products', models.CharField(max_length=100, null=True)),
                ('fuel_liters', models.CharField(max_length=100, null=True)),
                ('service_amount', models.CharField(max_length=100, null=True)),
                ('work_order', models.CharField(max_length=100, null=True)),
                ('odometer_start', models.CharField(max_length=100, null=True)),
                ('odometer_end', models.CharField(max_length=100, null=True)),
                ('v_brand', models.CharField(choices=[('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Isuzu', 'Isuzu'), ('Kia', 'Kia'), ('Masda', 'Masda'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Subaro', 'Subaro')], max_length=100, null=True)),
                ('v_make', models.CharField(max_length=100, null=True)),
                ('v_fuel_type', models.CharField(max_length=100, null=True)),
                ('v_model', models.CharField(max_length=100, null=True)),
                ('new_plate_number', models.CharField(max_length=100, null=True)),
                ('new_odometer_start', models.CharField(max_length=100, null=True)),
                ('new_odometer_end', models.CharField(max_length=100, null=True)),
                ('new_v_brand', models.CharField(choices=[('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Isuzu', 'Isuzu'), ('Kia', 'Kia'), ('Masda', 'Masda'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Subaro', 'Subaro')], max_length=100, null=True)),
                ('new_v_make', models.CharField(max_length=100, null=True)),
                ('new_v_fuel_type', models.CharField(max_length=100, null=True)),
                ('new_v_model', models.CharField(max_length=100, null=True)),
                ('gt_admin', models.CharField(choices=[('Approved', 'Approved')], max_length=100, null=True)),
                ('approval_date', models.DateField(null=True)),
                ('immediate_supervisor', models.CharField(choices=[('Ser Roy Dela Cruz', 'Ser Roy Dela Cruz'), ('Adolfo Carlos Umali', 'Adolfo Carlos Umali')], max_length=100, null=True)),
                ('im_approval_date', models.DateField(null=True)),
                ('voucher_docs1', models.CharField(max_length=100, null=True)),
                ('voucher_docs2', models.CharField(max_length=100, null=True)),
                ('voucher_docs3', models.CharField(max_length=100, null=True)),
                ('voucher_remarks', models.CharField(max_length=100, null=True)),
                ('voucher_forwarded', models.DateField(null=True)),
                ('EVO_SLA', models.CharField(max_length=10, null=True)),
                ('date_initiated', models.DateField(auto_now=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.EmployeeMasterlist')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.VehicleMasterList')),
            ],
        ),
    ]
