# Generated by Django 2.1.7 on 2019-11-08 05:58

from django.db import migrations, models
import voucher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense_voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=voucher.models.increment_Activity_id, max_length=100, null=True)),
                ('employee_id', models.CharField(max_length=100, null=True)),
                ('employee_fname', models.CharField(max_length=100, null=True)),
                ('employee_lname', models.CharField(max_length=100, null=True)),
                ('employee_group', models.CharField(max_length=100, null=True)),
                ('employee_cost', models.CharField(max_length=100, null=True)),
                ('new_employee_id', models.CharField(max_length=100, null=True)),
                ('new_employee_fname', models.CharField(max_length=100, null=True)),
                ('new_employee_lname', models.CharField(max_length=100, null=True)),
                ('new_employee_group', models.CharField(max_length=100, null=True)),
                ('new_employee_cost', models.CharField(max_length=100, null=True)),
                ('fleet_area', models.CharField(max_length=100, null=True)),
                ('received_voucher', models.DateField(null=True)),
                ('trans_type', models.CharField(max_length=100, null=True)),
                ('voucher_no', models.CharField(max_length=100, null=True)),
                ('voucher_amount', models.CharField(max_length=100, null=True)),
                ('voucher_type', models.CharField(max_length=100, null=True)),
                ('fuel_amount', models.CharField(max_length=100, null=True)),
                ('fuel_products', models.CharField(max_length=100, null=True)),
                ('fuel_liters', models.CharField(max_length=100, null=True)),
                ('service_amount', models.CharField(max_length=100, null=True)),
                ('work_order', models.CharField(max_length=100, null=True)),
                ('plate_number', models.CharField(max_length=100, null=True)),
                ('odometer_start', models.CharField(max_length=100, null=True)),
                ('odometer_end', models.CharField(max_length=100, null=True)),
                ('v_brand', models.CharField(max_length=100, null=True)),
                ('v_make', models.CharField(max_length=100, null=True)),
                ('v_fuel_type', models.CharField(max_length=100, null=True)),
                ('v_model', models.CharField(max_length=100, null=True)),
                ('new_plate_number', models.CharField(max_length=100, null=True)),
                ('new_odometer_start', models.CharField(max_length=100, null=True)),
                ('new_odometer_end', models.CharField(max_length=100, null=True)),
                ('new_v_brand', models.CharField(max_length=100, null=True)),
                ('new_v_make', models.CharField(max_length=100, null=True)),
                ('new_v_fuel_type', models.CharField(max_length=100, null=True)),
                ('new_v_model', models.CharField(max_length=100, null=True)),
                ('gt_admin', models.CharField(max_length=100, null=True)),
                ('immediate_supervisor', models.CharField(max_length=100, null=True)),
                ('approval_date', models.DateField(null=True)),
                ('voucher_docs1', models.CharField(max_length=100, null=True)),
                ('voucher_docs2', models.CharField(max_length=100, null=True)),
                ('voucher_docs3', models.CharField(max_length=100, null=True)),
                ('voucher_remarks', models.CharField(max_length=100, null=True)),
                ('voucher_forwarded', models.DateField(null=True)),
                ('EVO_SLA', models.CharField(max_length=10, null=True)),
                ('date_initiated', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
