# Generated by Django 2.1.7 on 2019-11-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_voucher',
            name='im_approval_date',
            field=models.DateField(null=True),
        ),
    ]
