# Generated by Django 2.1 on 2020-02-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_auto_20200203_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_voucher',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.EmployeeMasterlist'),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='plate_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.VehicleMasterList'),
        ),
    ]
