# Generated by Django 2.1.7 on 2019-11-11 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_expense_voucher_im_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_voucher',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.EmployeeMasterlist'),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='fleet_area',
            field=models.CharField(choices=[('The Globe Tower', 'The Globe Tower'), ('Visayas-Mindanao', 'Visayas-Mindanao')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='gt_admin',
            field=models.CharField(choices=[('Approved', 'Approved')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='immediate_supervisor',
            field=models.CharField(choices=[('Ser Roy Dela Cruz', 'Ser Roy Dela Cruz'), ('Adolfo Carlos Umali', 'Adolfo Carlos Umali')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_v_brand',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Isuzu', 'Isuzu'), ('Kia', 'Kia'), ('Masda', 'Masda'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Subaro', 'Subaro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='plate_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.VehicleMasterList'),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='trans_type',
            field=models.CharField(choices=[('Gas Reimbursements', 'Gas Reimbursements'), ('Car Parts Replacement', 'Car Parts Replacement'), ('GR and CPR', 'GR and CPR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='v_brand',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Isuzu', 'Isuzu'), ('Kia', 'Kia'), ('Masda', 'Masda'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Subaro', 'Subaro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Expense Voucher', 'Expense Voucher'), ('Petty Cash Voucher', 'Petty Cash Voucher'), ('EV and PCV', 'EV and PCV')], max_length=100, null=True),
        ),
    ]
