# Generated by Django 2.1 on 2020-02-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_auto_20200204_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_voucher',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='plate_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
