# Generated by Django 2.1.7 on 2020-02-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0004_historicalownership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalownership',
            old_name='date_docs_return',
            new_name='date_received_by',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='date_docs_return',
            new_name='date_received_by',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='date_pulled',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='lto_date_return',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='return_endorsementfleet',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='date_pulled',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='lto_date_return',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='return_endorsementfleet',
        ),
    ]
