# Generated by Django 2.1.7 on 2019-09-20 06:06

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True)),
                ('Bill_date', models.DateField(null=True)),
                ('Employee_id', models.CharField(max_length=100, null=True)),
                ('L_name', models.CharField(max_length=100, null=True)),
                ('F_name', models.CharField(max_length=100, null=True)),
                ('Assignee_company', models.CharField(max_length=100, null=True)),
                ('Cost_center', models.CharField(max_length=100, null=True)),
                ('Date_initiated', models.DateField(null=True)),
                ('O_Fname', models.CharField(max_length=100, null=True)),
                ('O_Lname', models.CharField(max_length=100, null=True)),
                ('O_cost_center', models.CharField(max_length=100, null=True)),
                ('Plate_no', models.CharField(max_length=100, null=True)),
                ('V_provider', models.CharField(max_length=100, null=True)),
                ('V_brand', models.CharField(max_length=100, null=True)),
                ('V_make', models.CharField(max_length=100, null=True)),
                ('D_vehicle', models.CharField(max_length=100, null=True)),
                ('S_rental', models.CharField(max_length=100, null=True)),
                ('E_rental', models.CharField(max_length=100, null=True)),
                ('R_duration', models.CharField(max_length=100, null=True)),
                ('R_Cost', models.CharField(max_length=100, null=True)),
                ('G_cost', models.CharField(max_length=100, null=True)),
                ('T_fee', models.CharField(max_length=100, null=True)),
                ('P_fee', models.CharField(max_length=100, null=True)),
                ('Del_fee', models.CharField(max_length=100, null=True)),
                ('Dri_fee', models.CharField(max_length=100, null=True)),
                ('M_cost', models.CharField(max_length=100, null=True)),
                ('O_expenses', models.CharField(max_length=100, null=True)),
                ('VAT', models.CharField(max_length=100, null=True)),
                ('T_expenses', models.CharField(max_length=100, null=True)),
                ('I_number', models.CharField(default=payment.models.increment_I_number, max_length=100, null=True)),
                ('I_amount', models.CharField(max_length=100, null=True)),
                ('R_purpose', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
