# Generated by Django 2.1.7 on 2020-01-16 04:51

from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True)),
                ('Bill_date', models.CharField(max_length=100, null=True)),
                ('Employee_id', models.CharField(max_length=100, null=True)),
                ('L_name', models.CharField(max_length=100, null=True)),
                ('F_name', models.CharField(max_length=100, null=True)),
                ('Assignee_company', models.CharField(max_length=100, null=True)),
                ('Cost_center', models.CharField(max_length=100, null=True)),
                ('Date_initiated', models.DateField(auto_now=True)),
                ('O_Fname', models.CharField(max_length=100, null=True)),
                ('O_Lname', models.CharField(max_length=100, null=True)),
                ('O_cost_center', models.CharField(max_length=100, null=True)),
                ('Plate_no', models.CharField(max_length=100, null=True)),
                ('V_provider', models.CharField(max_length=100, null=True)),
                ('V_brand', models.CharField(max_length=100, null=True)),
                ('V_make', models.CharField(max_length=100, null=True)),
                ('D_vehicle', models.CharField(max_length=100, null=True)),
                ('S_rental', models.CharField(max_length=100, null=True)),
                ('E_rental', models.CharField(max_length=100, null=True)),
                ('R_duration', models.CharField(max_length=100, null=True)),
                ('R_Cost', models.CharField(max_length=100, null=True)),
                ('G_cost', models.CharField(max_length=100, null=True)),
                ('T_fee', models.CharField(max_length=100, null=True)),
                ('P_fee', models.CharField(max_length=100, null=True)),
                ('Del_fee', models.CharField(max_length=100, null=True)),
                ('Dri_fee', models.CharField(max_length=100, null=True)),
                ('M_cost', models.CharField(max_length=100, null=True)),
                ('O_expenses', models.CharField(max_length=100, null=True)),
                ('VAT', models.CharField(max_length=100, null=True)),
                ('T_expenses', models.CharField(max_length=100, null=True)),
                ('I_number', models.CharField(default=payment.models.increment_I_number, max_length=100, null=True)),
                ('I_amount', models.CharField(max_length=100, null=True)),
                ('R_purpose', models.CharField(max_length=100, null=True)),
                ('C_SLA', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=payment.models.increment_Activity_id, max_length=20, null=True)),
                ('SOA_Date_received', models.DateField(null=True)),
                ('Fuel_provider', models.CharField(max_length=50, null=True)),
                ('SOA_billdate', models.DateField(null=True)),
                ('SOA_current_amount', models.CharField(max_length=50, null=True)),
                ('SOA_outstanding_amount', models.CharField(max_length=50, null=True)),
                ('Payee', models.CharField(choices=[('Globe', 'Globe'), ('Innove', 'Innove'), ('Byan', 'Bayan')], max_length=10, null=True)),
                ('SOA_attached', models.CharField(max_length=100, null=True)),
                ('Date_initiated', models.DateField(auto_now=True)),
                ('Payment_deadline', models.DateField(null=True)),
                ('Date_forwarded', models.DateField(null=True)),
                ('F_SLA', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=payment.models.increment_Activity_id, max_length=20)),
                ('PO_no', models.CharField(default=payment.models.increment_PO_no, max_length=100)),
                ('E_First_name', models.CharField(blank=True, max_length=50)),
                ('E_Last_name', models.CharField(blank=True, max_length=50)),
                ('V_deliverDate', models.DateField(null=True)),
                ('Plate_no', models.CharField(blank=True, max_length=20)),
                ('V_model', models.CharField(blank=True, max_length=100)),
                ('V_brand', models.CharField(blank=True, max_length=100)),
                ('V_make', models.CharField(blank=True, max_length=100)),
                ('V_dealer', models.CharField(blank=True, max_length=100)),
                ('LTO_documents', models.DateField(null=True)),
                ('Docs_plate_no', models.CharField(blank=True, max_length=50)),
                ('LTO_stickers', models.CharField(blank=True, max_length=100)),
                ('Sticker_fields', models.CharField(blank=True, max_length=100)),
                ('Date_initial', models.DateField(null=True)),
                ('First_payment', models.CharField(blank=True, max_length=100)),
                ('LTO_charges', models.CharField(blank=True, max_length=100)),
                ('Outstanding_balance', models.CharField(blank=True, max_length=100)),
                ('Date_final', models.DateField(null=True)),
                ('Routing_remarks', models.CharField(blank=True, max_length=100)),
                ('V_SLA', models.CharField(blank=True, max_length=10)),
                ('Next_process', models.CharField(blank=True, max_length=100)),
                ('Date_initiated', models.DateField(auto_now=True)),
                ('A_employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.EmployeeMasterlist')),
            ],
        ),
    ]
