# Generated by Django 2.1.7 on 2019-10-10 06:24

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='A_employee_ID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='E_First_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
