# Generated by Django 2.1.7 on 2019-10-10 06:28

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20191010_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='A_employee_ID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Date_final',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Date_initial',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Docs_plate_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='E_Last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='First_payment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='LTO_charges',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='LTO_documents',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='LTO_stickers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Next_process',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Outstanding_balance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Routing_remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Sticker_fields',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='V_SLA',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='V_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='V_dealer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='V_deliverDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='V_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='V_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='V_plateNo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
