# Generated by Django 2.1.7 on 2019-10-10 06:35

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20191010_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Date_initial',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='LTO_documents',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='PO_no',
            field=models.CharField(default=payment.models.increment_PO_no, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='V_deliverDate',
            field=models.DateField(blank=True),
        ),
    ]
