# Generated by Django 2.1.7 on 2019-10-11 06:08

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20191011_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_supplier',
            name='Date_initiated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fuel_supplier',
            name='Payee',
            field=models.CharField(choices=[('Globe', 'Globe'), ('Innove', 'Innove'), ('Byan', 'Bayan')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20),
        ),
    ]
