# Generated by Django 2.1.7 on 2020-02-20 07:09

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20200220_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvehicle_repair_payment',
            name='history_user',
        ),
        migrations.AddField(
            model_name='vehicle_repair_payment',
            name='date_initiated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_supplier',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcarrental',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfuel_supplier',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehiclepayment',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20),
        ),
        migrations.DeleteModel(
            name='HistoricalVehicle_Repair_payment',
        ),
    ]
