# Generated by Django 2.1.7 on 2020-02-21 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0009_auto_20200220_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVehicle_Repair_payment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Activity_id', models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True)),
                ('request_date', models.DateField(null=True)),
                ('employee', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('group_section', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('v_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('v_make', models.CharField(blank=True, max_length=100, null=True)),
                ('v_model', models.CharField(blank=True, max_length=100, null=True)),
                ('chassis', models.CharField(blank=True, max_length=100, null=True)),
                ('band', models.CharField(blank=True, max_length=100, null=True)),
                ('cond_sticker', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dealership', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=20, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('Preventive Maintenance', 'Preventive Maintenance'), ('Corective Maitenance', 'Corective Maitenance'), ('Battery', 'Battery'), ('Tire', 'Tire')], max_length=100, null=True)),
                ('date_initiated', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vehicle_ repair_payment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_supplier',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcarrental',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfuel_supplier',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehiclepayment',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20),
        ),
    ]
