# Generated by Django 2.1.7 on 2020-01-24 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0005_auto_20200123_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemasterlist',
            old_name='Employee_Id',
            new_name='Employee',
        ),
    ]
