# Generated by Django 2.1.7 on 2020-03-09 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import report.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalvehicle_report',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Activity_id', models.CharField(default=report.models.increment_Activity_id, max_length=100, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('v_accident_type', models.CharField(blank=True, max_length=100, null=True)),
                ('support_docs', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('v_model', models.CharField(blank=True, max_length=100, null=True)),
                ('v_make', models.CharField(blank=True, max_length=100, null=True)),
                ('cond_sticker', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_no', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_company', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_group', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_division', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_dept', models.CharField(blank=True, max_length=100, null=True)),
                ('sup_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sup_employee_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('sup_employee_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('inform_assignee', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_inspection', models.CharField(blank=True, max_length=100, null=True)),
                ('inspection_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('date_filed_alarm', models.CharField(blank=True, max_length=100, null=True)),
                ('date_cert_received', models.CharField(blank=True, max_length=100, null=True)),
                ('date_forwarded', models.CharField(blank=True, max_length=100, null=True)),
                ('date_initiated', models.DateField(blank=True, editable=False, null=True)),
                ('MVAR_SLA', models.CharField(max_length=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vehicle_report',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='vehicle_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=report.models.increment_Activity_id, max_length=100, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('v_accident_type', models.CharField(blank=True, max_length=100, null=True)),
                ('support_docs', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('v_model', models.CharField(blank=True, max_length=100, null=True)),
                ('v_make', models.CharField(blank=True, max_length=100, null=True)),
                ('cond_sticker', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_no', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_company', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_group', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_division', models.CharField(blank=True, max_length=100, null=True)),
                ('a_employee_dept', models.CharField(blank=True, max_length=100, null=True)),
                ('sup_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sup_employee_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('sup_employee_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('inform_assignee', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_inspection', models.CharField(blank=True, max_length=100, null=True)),
                ('inspection_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('date_filed_alarm', models.CharField(blank=True, max_length=100, null=True)),
                ('date_cert_received', models.CharField(blank=True, max_length=100, null=True)),
                ('date_forwarded', models.CharField(blank=True, max_length=100, null=True)),
                ('date_initiated', models.DateField(auto_now=True, null=True)),
                ('MVAR_SLA', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
