# Generated by Django 2.1 on 2020-02-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20200203_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_report',
            name='date_cert_received',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_report',
            name='date_filed_alarm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_report',
            name='date_forwarded',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_report',
            name='date_of_inspection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_report',
            name='inform_assignee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
