# Generated by Django 2.1.7 on 2020-01-15 06:29

from django.db import migrations, models
import masterlist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMasterlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100, null=True)),
                ('Employee_Id', models.CharField(max_length=100, null=True)),
                ('Last_name', models.CharField(max_length=50, null=True)),
                ('First_name', models.CharField(max_length=50, null=True)),
                ('Middle_name', models.CharField(max_length=5, null=True)),
                ('Suffix', models.CharField(max_length=20, null=True)),
                ('External_role', models.CharField(max_length=100, null=True)),
                ('Job_category', models.CharField(max_length=100, null=True)),
                ('Hiring_date', models.DateField(null=True)),
                ('Tenure', models.FloatField(null=True)),
                ('Band', models.CharField(max_length=50, null=True)),
                ('Cost_center', models.CharField(max_length=100, null=True)),
                ('DIV_code', models.CharField(max_length=100, null=True)),
                ('Group', models.CharField(max_length=100, null=True)),
                ('Division', models.CharField(max_length=100, null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('Section', models.CharField(max_length=100, null=True)),
                ('Unit', models.CharField(max_length=100, null=True)),
                ('Sub_unit', models.CharField(max_length=100, null=True)),
                ('IS_ID', models.CharField(max_length=100, null=True)),
                ('IS_lastname', models.CharField(max_length=100, null=True)),
                ('IS_firstname', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('Area2', models.CharField(max_length=100, null=True)),
                ('Benefit', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMasterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_Id', models.CharField(default=masterlist.models.increment_Activity_Id, max_length=100, null=True)),
                ('NO', models.CharField(default=masterlist.models.increment_NO, max_length=100, null=True)),
                ('PLATE_NO', models.CharField(max_length=100, null=True)),
                ('CS_NO', models.CharField(max_length=100, null=True)),
                ('CR_NAME', models.CharField(max_length=100, null=True)),
                ('PLATE_ENDING', models.CharField(max_length=100, null=True)),
                ('REGISTRATION_MONTH', models.CharField(max_length=100, null=True)),
                ('MODEL', models.CharField(max_length=100, null=True)),
                ('BRAND', models.CharField(choices=[('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Mitsubishi', 'Mitsubishi'), ('Ford', 'Ford'), ('Masda', 'Masda'), ('Isuzu', 'Isuzu'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('SuZuki', 'Suzuki'), ('Chevrolet', 'Chevrolet')], max_length=100, null=True)),
                ('VEHICLE_MAKE', models.CharField(max_length=100, null=True)),
                ('ENGINE_NO', models.CharField(max_length=100, null=True)),
                ('CHASSIS_NO', models.CharField(max_length=100, null=True)),
                ('MV_FILE_NO', models.CharField(max_length=100, null=True)),
                ('VEHICLE_TYPE', models.CharField(max_length=100, null=True)),
                ('ASSIGNEE_LAST_NAME', models.CharField(max_length=100, null=True)),
                ('ASSIGNEE_FIRST_NAME', models.CharField(max_length=100, null=True)),
                ('VEHICLE_CATEGORY', models.CharField(max_length=100, null=True)),
                ('BAND_LEVEL', models.CharField(max_length=100, null=True)),
                ('BENEFIT_GROUP', models.CharField(max_length=100, null=True)),
                ('COST_CENTER', models.CharField(max_length=100, null=True)),
                ('GROUP', models.CharField(max_length=100, null=True)),
                ('DIVISION', models.CharField(max_length=100, null=True)),
                ('DEPARTMENT', models.CharField(max_length=100, null=True)),
                ('SECTION', models.CharField(max_length=100, null=True)),
                ('IS_ID', models.CharField(max_length=100, null=True)),
                ('IS_LAST_NAME', models.CharField(max_length=100, null=True)),
                ('IS_FIRST_NAME', models.CharField(max_length=100, null=True)),
                ('LOCATION', models.CharField(max_length=100, null=True)),
                ('ORIGINAL_OR_DATE', models.DateField(null=True)),
                ('ACQ_DATE', models.DateField(null=True)),
                ('ACQ_COST', models.CharField(max_length=100, null=True)),
                ('ASSET_NO', models.CharField(max_length=100, null=True)),
                ('EQUIPMENT_NO', models.CharField(max_length=100, null=True)),
                ('PO_NO', models.CharField(max_length=100, null=True)),
                ('PLATE_NUMBER_RELEASE_DATE', models.DateField(null=True)),
                ('Employee_Id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
