# Generated by Django 2.1.7 on 2019-10-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemasterlist',
            old_name='Sold_vehicle',
            new_name='Fname_assignee',
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='Lname_assignee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeemasterlist',
            name='Employee_Id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
