# Generated by Django 2.1.7 on 2020-02-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='CS_NO',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='CS_NO',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
