# Generated by Django 2.1.7 on 2020-01-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0002_auto_20200123_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Employee_Id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
