# Generated by Django 2.1.7 on 2019-11-15 06:02

from django.db import migrations, models
import masterlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0002_auto_20191115_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='No',
            field=models.CharField(default=masterlist.models.increment_No, max_length=50, null=True),
        ),
    ]
