# Generated by Django 2.1.7 on 2019-10-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0002_auto_20191014_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemasterlist',
            name='First_name_assignee',
        ),
        migrations.RemoveField(
            model_name='vehiclemasterlist',
            name='Last_name_assignee',
        ),
    ]
