# Generated by Django 2.1.7 on 2020-02-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0003_auto_20200224_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='COC_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='Last_Registration_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='Remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='Smoke_Emission_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='COC_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='Last_Registration_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='Remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='Smoke_Emission_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
