# Generated by Django 2.1.7 on 2019-11-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0003_auto_20191115_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='original_OR_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='plateNo_release',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='reg_month',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
