# Generated by Django 2.1.7 on 2019-10-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0003_auto_20191015_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Brand',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Mitsubishi', 'Mitsubishi'), ('Ford', 'Ford'), ('Masda', 'Masda'), ('Isuzu', 'Isuzu'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('SuZuki', 'Suzuki'), ('Chevrolet', 'Chevrolet')], max_length=50, null=True),
        ),
    ]
