# Generated by Django 2.1.7 on 2019-11-28 06:01

from django.db import migrations, models
import django.db.models.deletion
import masterlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0004_auto_20191127_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMasterListNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.CharField(default=masterlist.models.increment_No, max_length=50, null=True)),
                ('Plate_no', models.CharField(max_length=50, null=True)),
                ('Conduction_Sticker', models.CharField(max_length=100, null=True)),
                ('CR_name', models.CharField(max_length=100, null=True)),
                ('Plate_Ending', models.CharField(max_length=20, null=True)),
                ('Model', models.CharField(max_length=50, null=True)),
                ('Brand', models.CharField(max_length=50, null=True)),
                ('Vehicle_make', models.CharField(max_length=100, null=True)),
                ('Engine_No', models.CharField(max_length=100, null=True)),
                ('Chassis_no', models.CharField(max_length=100, null=True)),
                ('MV_file_no', models.CharField(max_length=100, null=True)),
                ('vehicle_type', models.CharField(max_length=100, null=True)),
                ('assignee_lname', models.CharField(max_length=50, null=True)),
                ('Vehicle_category', models.CharField(max_length=100, null=True)),
                ('Band_level', models.CharField(max_length=50, null=True)),
                ('Band_Benefit', models.CharField(max_length=50, null=True)),
                ('Cost_center', models.CharField(max_length=100, null=True)),
                ('Group', models.CharField(max_length=100, null=True)),
                ('Division', models.CharField(max_length=100, null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('Section', models.CharField(max_length=100, null=True)),
                ('IS_ID', models.CharField(max_length=100, null=True)),
                ('IS_firstname', models.CharField(max_length=100, null=True)),
                ('IS_lastname', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('original_or', models.DateField(null=True)),
                ('Aquisition_date', models.DateField(null=True)),
                ('Aquisition_cost', models.CharField(max_length=100, null=True)),
                ('Asset_no', models.CharField(max_length=100, null=True)),
                ('equipt_no', models.CharField(max_length=50, null=True)),
                ('po_no', models.DateField(null=True)),
                ('plateNo_release', models.DateField(null=True)),
                ('Employee_Id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.EmployeeMasterlist')),
            ],
        ),
    ]
