# Generated by Django 2.1.7 on 2020-03-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0004_auto_20200224_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='Remarks',
            field=models.CharField(blank=True, choices=[('Without Last Registration Date', 'Without Last Registration Date'), ('Without Smoke Emission Date', 'Without Smoke Emission Date'), ('Without COC Date', 'Without COC Date'), ('Complete', 'Complete')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Remarks',
            field=models.CharField(blank=True, choices=[('Without Last Registration Date', 'Without Last Registration Date'), ('Without Smoke Emission Date', 'Without Smoke Emission Date'), ('Without COC Date', 'Without COC Date'), ('Complete', 'Complete')], max_length=100, null=True),
        ),
    ]
