# Generated by Django 2.1.7 on 2019-10-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0004_auto_20191015_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Brand',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
