# Generated by Django 2.1.7 on 2020-03-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0005_auto_20200303_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='leasing_remark',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='leasing_remark',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
