# Generated by Django 2.1.7 on 2020-01-24 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0006_auto_20200124_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='ACQ_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.EmployeeMasterlist'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='MODEL',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='PLATE_ENDING',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='PLATE_NUMBER_RELEASE_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='REGISTRATION_MONTH',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
