# Generated by Django 2.1.7 on 2020-02-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0008_auto_20200130_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemasterlist',
            name='External_role',
        ),
        migrations.RemoveField(
            model_name='employeemasterlist',
            name='Hiring_date',
        ),
        migrations.RemoveField(
            model_name='employeemasterlist',
            name='Job_category',
        ),
        migrations.RemoveField(
            model_name='employeemasterlist',
            name='Tenure',
        ),
    ]
