# Generated by Django 2.1.7 on 2020-02-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0009_auto_20200218_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemasterlist',
            name='Middle_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
