# Generated by Django 2.1.7 on 2020-02-19 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0006_auto_20200219_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFuel_supplier',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Activity_id', models.CharField(default=payment.models.increment_Activity_id, max_length=20, null=True)),
                ('SOA_Date_received', models.CharField(blank=True, max_length=100)),
                ('Fuel_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('SOA_billdate', models.CharField(blank=True, max_length=100)),
                ('SOA_current_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('SOA_outstanding_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('Payee', models.CharField(blank=True, choices=[('Globe', 'Globe'), ('Innove', 'Innove'), ('Byan', 'Bayan')], max_length=10, null=True)),
                ('SOA_attached', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_initiated', models.DateField(blank=True, editable=False)),
                ('Payment_deadline', models.CharField(blank=True, max_length=100)),
                ('Date_forwarded', models.CharField(blank=True, max_length=100)),
                ('F_SLA', models.CharField(blank=True, max_length=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fuel_supplier',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVehiclePayment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Activity_id', models.CharField(default=payment.models.increment_Activity_id, max_length=20)),
                ('PO_no', models.CharField(default=payment.models.increment_PO_no, max_length=100)),
                ('A_employee_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('E_First_name', models.CharField(blank=True, max_length=50, null=True)),
                ('E_Last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('V_deliverDate', models.CharField(blank=True, max_length=100, null=True)),
                ('Plate_no', models.CharField(blank=True, max_length=20, null=True)),
                ('V_model', models.CharField(blank=True, max_length=100, null=True)),
                ('V_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('V_make', models.CharField(blank=True, max_length=100, null=True)),
                ('V_dealer', models.CharField(blank=True, max_length=100, null=True)),
                ('LTO_documents', models.CharField(blank=True, max_length=100, null=True)),
                ('Docs_plate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('LTO_stickers', models.CharField(blank=True, max_length=100, null=True)),
                ('Sticker_fields', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_initial', models.CharField(blank=True, max_length=100, null=True)),
                ('First_payment', models.CharField(blank=True, max_length=100, null=True)),
                ('LTO_charges', models.CharField(blank=True, max_length=100, null=True)),
                ('Outstanding_balance', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_final', models.CharField(blank=True, max_length=100, null=True)),
                ('Routing_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('V_SLA', models.CharField(blank=True, max_length=10, null=True)),
                ('Next_process', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_initiated', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vehicle payment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcarrental',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayment',
            name='Activity_id',
            field=models.CharField(default=payment.models.increment_Activity_id, max_length=20),
        ),
    ]
