# Generated by Django 2.1 on 2020-02-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_voucher',
            name='approval_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='employee_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='employee_fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='employee_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='employee_lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='fleet_area',
            field=models.CharField(blank=True, choices=[('The Globe Tower', 'The Globe Tower'), ('Visayas-Mindanao', 'Visayas-Mindanao')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='fuel_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='fuel_liters',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='fuel_products',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='gt_admin',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='im_approval_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='immediate_supervisor',
            field=models.CharField(blank=True, choices=[('Ser Roy Dela Cruz', 'Ser Roy Dela Cruz'), ('Adolfo Carlos Umali', 'Adolfo Carlos Umali')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_employee_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_employee_fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_employee_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_employee_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_employee_lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_odometer_end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_odometer_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_plate_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_v_brand',
            field=models.CharField(blank=True, choices=[('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Isuzu', 'Isuzu'), ('Kia', 'Kia'), ('Masda', 'Masda'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Subaro', 'Subaro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_v_fuel_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_v_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='new_v_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='odometer_end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='odometer_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='plate_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='received_voucher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='service_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='trans_type',
            field=models.CharField(blank=True, choices=[('Gas Reimbursements', 'Gas Reimbursements'), ('Car Parts Replacement', 'Car Parts Replacement'), ('GR and CPR', 'GR and CPR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='v_brand',
            field=models.CharField(blank=True, choices=[('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Isuzu', 'Isuzu'), ('Kia', 'Kia'), ('Masda', 'Masda'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Subaro', 'Subaro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='v_fuel_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='v_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='v_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='voucher_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='voucher_docs1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='voucher_docs2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='voucher_docs3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='voucher_forwarded',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='voucher_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='voucher_type',
            field=models.CharField(blank=True, choices=[('Expense Voucher', 'Expense Voucher'), ('Petty Cash Voucher', 'Petty Cash Voucher'), ('EV and PCV', 'EV and PCV')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense_voucher',
            name='work_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
