# Generated by Django 2.1.7 on 2019-10-23 02:36

from django.db import migrations, models
import django.db.models.deletion
import request.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True)),
                ('Date_received', models.DateField(null=True)),
                ('Assignee_Fname', models.CharField(max_length=100, null=True)),
                ('Assignee_Lname', models.CharField(max_length=100, null=True)),
                ('Assignee_No', models.CharField(max_length=50, null=True)),
                ('Assignee_Company', models.CharField(max_length=200, null=True)),
                ('Assignee_band', models.CharField(max_length=100, null=True)),
                ('Assignee_Dept', models.CharField(max_length=100, null=True)),
                ('Assignee_Cost', models.FloatField(null=True)),
                ('Assignee_Div', models.CharField(max_length=100, null=True)),
                ('Assignee_Loc', models.CharField(max_length=200, null=True)),
                ('Assignee_Section', models.CharField(max_length=100, null=True)),
                ('Assignee_Designation', models.CharField(max_length=100, null=True)),
                ('Assignee_ATD', models.CharField(max_length=100, null=True)),
                ('Vendor_name', models.CharField(max_length=100, null=True)),
                ('Date', models.DateField(null=True)),
                ('Up_to', models.CharField(max_length=100, null=True)),
                ('Time', models.TimeField(null=True)),
                ('Place_of_del', models.CharField(max_length=100, null=True)),
                ('type_rental', models.CharField(max_length=50, null=True)),
                ('Cost_center', models.FloatField(null=True)),
                ('Rental_period', models.FloatField(null=True)),
                ('Destination', models.CharField(max_length=100, null=True)),
                ('Delivery_date', models.DateField(null=True)),
                ('End_user', models.CharField(max_length=100, null=True)),
                ('Type_of_vehicle', models.CharField(max_length=50, null=True)),
                ('Plate_no', models.CharField(max_length=50, null=True)),
                ('Immediate_supervisor', models.CharField(max_length=50, null=True)),
                ('CR_SLA', models.FloatField(null=True)),
                ('Date_initiated', models.DateField(auto_now=True)),
                ('A_Employee_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterlist.EmployeeMasterlist')),
            ],
        ),
    ]
