# Generated by Django 2.1.7 on 2019-10-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Immediate_supervisor',
            field=models.CharField(choices=[('Ser Roy DelaCruz', 'Ser Roy DelaCruz'), ('Adolfo Carlos Umali', 'Adolfo Carlos Umali')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='type_rental',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=50, null=True),
        ),
    ]
