# Generated by Django 2.1.7 on 2019-10-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20191024_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentalrequest',
            name='CR_SLA',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Type_of_vehicle',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('VAN', 'VAN')], max_length=50, null=True),
        ),
    ]
