# Generated by Django 2.1.7 on 2019-11-04 02:46

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20191031_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True)),
                ('request_date', models.DateField(null=True)),
                ('employee_Id', models.CharField(max_length=100, null=True)),
                ('cost_center', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('Last_name', models.CharField(max_length=100, null=True)),
                ('contact_no', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('group_section', models.CharField(max_length=100, null=True)),
                ('plate_no', models.CharField(max_length=100, null=True)),
                ('v_brand', models.CharField(max_length=100, null=True)),
                ('engine', models.CharField(max_length=100, null=True)),
                ('v_make', models.CharField(max_length=100, null=True)),
                ('v_model', models.CharField(max_length=100, null=True)),
                ('chassis', models.CharField(max_length=100, null=True)),
                ('band', models.CharField(max_length=100, null=True)),
                ('cond_sticker', models.CharField(max_length=100, null=True)),
                ('equipment_no', models.CharField(max_length=100, null=True)),
                ('fleet_area', models.CharField(choices=[('The Globe Tower', 'The Globe Tower'), ('Visayas-Mindanao', 'Visayas-Mindanao ')], max_length=100, null=True)),
                ('maintenance_type1', models.CharField(choices=[('Preventive Maintenance', 'Preventive Maintenance'), ('Corective Maitenance', 'Corective Maitenance'), ('Battery', 'Battery'), ('Tire', 'Tire')], max_length=100, null=True)),
                ('scope_work1', models.CharField(max_length=100, null=True)),
                ('maintenance_type2', models.CharField(choices=[('Preventive Maintenance', 'Preventive Maintenance'), ('Corective Maitenance', 'Corective Maitenance'), ('Battery', 'Battery'), ('Tire', 'Tire')], max_length=100, null=True)),
                ('scope_work2', models.CharField(max_length=100, null=True)),
                ('recommendations', models.CharField(max_length=100, null=True)),
                ('service_reminder', models.CharField(max_length=100, null=True)),
                ('verified_by', models.CharField(choices=[('Shane Santos', 'Shane Santos')], max_length=100, null=True)),
                ('particulars', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('work_order1', models.CharField(max_length=100, null=True)),
                ('work_order2', models.CharField(max_length=100, null=True)),
                ('dateworke_created', models.DateField(null=True)),
                ('Shop_vendor', models.CharField(choices=[('GR8', 'GR8'), ('Rapide', 'Rapide'), ('EV', 'EV')], max_length=100, null=True)),
                ('date_forwarded', models.CharField(max_length=100, null=True)),
                ('estimate_no', models.CharField(max_length=100, null=True)),
                ('maintenance_amount', models.CharField(max_length=100, null=True)),
                ('less_discount', models.CharField(max_length=100, null=True)),
                ('estimate_remarks', models.CharField(max_length=100, null=True)),
                ('estimate_attached', models.CharField(max_length=100, null=True)),
                ('approvedby', models.CharField(choices=[('Ser Roy Perluval Dela Cruz', 'Ser Roy Perluval Dela Cruz'), ('Adolfo Carlos Umali', 'Adolfo Carlos Umali')], max_length=100, null=True)),
                ('meter_reading', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gas_card',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_vehicle',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
    ]
