# Generated by Django 2.1.7 on 2019-10-28 02:26

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20191024_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True)),
                ('date_received', models.DateField(null=True)),
                ('application_type', models.CharField(choices=[('New Card', 'Daily'), ('Transfer Acountability', 'Transfer Acountability'), ('Cancel - Disposal of Vehicle', 'Cancel - Disposal of Vehicle'), ('Cancel - Resignation of User', 'Cancel - Resignation of User'), ('Replacement - Damage', 'Replacement - Damage'), ('Replacement - Lose', 'Replacement - Lose'), ('Others - Adjust Credit Limit', 'Others - Adjust Credit Limit'), ('Others - Change of Product Restriction', 'Others - Change of Product Restriction'), ('Others - Update Cost Center', 'Others - Update Cost Center')], max_length=100, null=True)),
                ('fleet_provider', models.CharField(choices=[('Petron', 'Petron'), ('Shell', 'Shell')], max_length=100, null=True)),
                ('fleetcard_type', models.CharField(choices=[('Single', 'Single'), ('Driver', 'Driver'), ('Vehicle', 'Vehicle')], max_length=100, null=True)),
                ('fuel_limit_amount', models.CharField(max_length=100, null=True)),
                ('fuel_limit_quantity', models.CharField(max_length=100, null=True)),
                ('products_restriction', models.CharField(choices=[('S: Super Only', 'S: Super Only'), ('U: Super Unleaded Only', 'U: Super Unleaded Only'), ('R: Regular Only', 'R: Regular Only'), ('X: Velocity', 'X: Velocity'), ('D: Diesoline Only', 'D: Diesoline Only'), ('L: Lubricant Only', 'L: Lubricant Only'), ('V: Service Only', 'V: Service Only'), ('C: Convenience store items, sundries, accesories', 'C: Convenience store items, sundries, accesories')], max_length=100, null=True)),
                ('req_employee_id', models.CharField(max_length=100, null=True)),
                ('req_fname', models.CharField(max_length=100, null=True)),
                ('req_lname', models.CharField(max_length=100, null=True)),
                ('req_title', models.CharField(max_length=100, null=True)),
                ('req_cost_center', models.CharField(max_length=100, null=True)),
                ('atd_no', models.CharField(max_length=100, null=True)),
                ('temporary_atd', models.CharField(max_length=100, null=True)),
                ('new_emp_id', models.CharField(max_length=100, null=True)),
                ('new_emp_fname', models.CharField(max_length=100, null=True)),
                ('new_emp_lname', models.CharField(max_length=100, null=True)),
                ('new_emp_cost', models.CharField(max_length=100, null=True)),
                ('new_temp_atd', models.CharField(max_length=100, null=True)),
                ('new_assignee', models.CharField(max_length=100, null=True)),
                ('cost_center_code', models.CharField(max_length=100, null=True)),
                ('cancellation', models.CharField(max_length=100, null=True)),
                ('plate_no', models.CharField(max_length=100, null=True)),
                ('con_sticker', models.CharField(max_length=100, null=True)),
                ('model_year', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('make', models.CharField(max_length=100, null=True)),
                ('fuel_type', models.CharField(max_length=100, null=True)),
                ('new_plate_no', models.CharField(max_length=100, null=True)),
                ('new_cond_sticker', models.CharField(max_length=100, null=True)),
                ('new_model_year', models.CharField(max_length=100, null=True)),
                ('new_vbrand', models.CharField(max_length=100, null=True)),
                ('new_vmake', models.CharField(max_length=100, null=True)),
                ('new_vfuel_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
    ]
