# Generated by Django 2.1.7 on 2020-01-31 02:57

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20200131_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gas_card',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_vehicle',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
    ]
