# Generated by Django 2.1.7 on 2019-11-04 06:20

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20191104_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_repair',
            old_name='dateworke_created',
            new_name='datework_created',
        ),
        migrations.RenameField(
            model_name='vehicle_repair',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='vehicle_repair',
            name='VRR_SLA',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gas_card',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_vehicle',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
    ]
