# Generated by Django 2.1.7 on 2020-01-31 02:58

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20200131_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Assignee_Cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Cost_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Rental_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gas_card',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_vehicle',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
    ]
