# Generated by Django 2.1.7 on 2019-10-28 06:05

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20191028_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas_card',
            name='approved_by',
            field=models.CharField(choices=[('Ser Roy Perluval Dela Cruz', 'Ser Roy Perluval Dela Cruz')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gas_card',
            name='date_summitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gas_card',
            name='fleet_card_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gas_card',
            name='fleet_date_release',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gas_card',
            name='fleet_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gas_card',
            name='person_release',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gas_card',
            name='cancellation',
            field=models.CharField(choices=[('Disposal Of Vehicle', 'Disposal Of Vehicle'), ('Resignation of User', 'Resignation of User')], max_length=100, null=True),
        ),
    ]
