# Generated by Django 2.1.7 on 2019-10-29 01:38

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20191028_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas_card',
            name='GCR_SLA',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gas_card',
            name='date_initiated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
    ]
