# Generated by Django 2.1.7 on 2019-10-29 07:22

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20191029_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True)),
                ('request_date', models.DateField(null=True)),
                ('req_employee_id', models.CharField(max_length=100, null=True)),
                ('req_lname', models.CharField(max_length=100, null=True)),
                ('req_fname', models.CharField(max_length=100, null=True)),
                ('assignee_employee_id', models.CharField(max_length=100, null=True)),
                ('assignee_group', models.CharField(max_length=100, null=True)),
                ('assignee_fname', models.CharField(max_length=100, null=True)),
                ('assignee_lname', models.CharField(max_length=100, null=True)),
                ('assignee_costcenter', models.CharField(max_length=100, null=True)),
                ('assignee_section', models.CharField(max_length=100, null=True)),
                ('assignee_location', models.CharField(max_length=100, null=True)),
                ('assignee_atd', models.CharField(max_length=100, null=True)),
                ('new_employee_id', models.CharField(max_length=100, null=True)),
                ('new_employee_fname', models.CharField(max_length=100, null=True)),
                ('new_employee_lname', models.CharField(max_length=100, null=True)),
                ('new_employee_cost', models.CharField(max_length=100, null=True)),
                ('new_temporary_atd', models.CharField(max_length=100, null=True)),
                ('prefered_vehicle', models.CharField(max_length=100, null=True)),
                ('E_plate_no', models.CharField(max_length=100, null=True)),
                ('E_con_sticker', models.CharField(max_length=100, null=True)),
                ('E_model_year', models.CharField(max_length=100, null=True)),
                ('E_brand', models.CharField(max_length=100, null=True)),
                ('E_make', models.CharField(max_length=100, null=True)),
                ('E_type', models.CharField(max_length=100, null=True)),
                ('approved_by', models.CharField(max_length=100, null=True)),
                ('approved_date', models.DateField(null=True)),
                ('vehicle_provider', models.CharField(max_length=100, null=True)),
                ('vehicle_plate_no', models.CharField(max_length=100, null=True)),
                ('vehicle_CS_no', models.CharField(max_length=100, null=True)),
                ('vehicle_model', models.CharField(max_length=100, null=True)),
                ('vehicle_brand', models.CharField(max_length=100, null=True)),
                ('vehicle_make', models.CharField(max_length=100, null=True)),
                ('vehicle_fuel_type', models.CharField(max_length=100, null=True)),
                ('SVV_SLA', models.CharField(max_length=10, null=True)),
                ('date_initiated', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gas_card',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
    ]
