# Generated by Django 2.1.7 on 2019-11-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='date_notorized',
            new_name='date_notarized',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='deed_of_sale',
        ),
    ]
