# Generated by Django 2.1.7 on 2019-11-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0002_auto_20191107_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='confirmation_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Final Pay', 'Final Pay')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='purpose',
            field=models.CharField(choices=[('Deceased', 'Deceased'), ('Early Availment', 'Early Availment'), ('End of Car Plan', 'End of Car Plan'), ('FSSV Availment', 'FSSV Availment'), ('Promotion', 'Promotion'), ('Resigned', 'Resigned'), ('Shift from Non-Sales to Sales', 'Shift from Non-Sales to Sales'), ('Shift from Sales to Non-Sales', 'Shift from Sales to Non-Sales'), ('Winning Bidder', 'Winning Bidder')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='vendor',
            field=models.CharField(choices=[('Globe Telecome', 'Globe Telecome'), ('Innove', 'Innove'), ('Bayantel Communication', 'Bayantel Communication')], max_length=100, null=True),
        ),
    ]
