# Generated by Django 2.1.7 on 2019-11-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0003_auto_20191108_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='plate_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.VehicleMasterList'),
        ),
    ]
