# Generated by Django 2.1.7 on 2020-02-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0005_auto_20200221_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalownership',
            old_name='tmg_date_out',
            new_name='tmg_location',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='tmg_date_out',
            new_name='tmg_location',
        ),
    ]
