# Generated by Django 2.1.7 on 2020-02-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0006_auto_20200221_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalownership',
            name='lto_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='lto_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
