# Generated by Django 2.1.7 on 2019-11-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20191022_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fata_monitoring',
            name='Recipient_Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Recipient_Employee', to='masterlist.EmployeeMasterlist'),
        ),
        migrations.AlterField(
            model_name='fata_monitoring',
            name='Transferor_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Transferor_employee', to='masterlist.EmployeeMasterlist'),
        ),
    ]
