# Generated by Django 2.1 on 2020-02-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20200203_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='fata_monitoring',
            name='Date_initiated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fata_monitoring',
            name='Date_endorsed_Innove',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
